hwdb:
  - hwdb.d/**/*
units:
  - units/**/*
documentation:
  - any: ['man/*', 'docs/*', 'NEWS']
network:
  - any: ['src/libsystemd-network/**/*', 'src/network/**/*']
udev:
  - any: ['src/udev/**/*', 'src/libudev/*']
selinux: 
  - *selinux*
apparmor: 
  - '**/apparmor*'
meson:
  - any: ['**/meson.build', 'meson_option.txt']
busctl:
  - src/busctl/*
systemctl: 
  - src/systemctl/*
journal:
  - src/journal/*
journal-remote:
  - src/journal-remote/*
