---
# vi: ts=2 sw=2 et:

extraction:
  cpp:
    prepare:
      packages:
        - libfdisk-dev
       # The current Ubuntu release (Eoan) doesn't have the libfido2 packages.
       # Let's wait until the LGTM infra is upgraded to at least Ubuntu Focal.
       #- libfido2-dev
        - libp11-kit-dev
        - libpwquality-dev
        - libssl-dev
        - libtss2-dev
        - libtss2-esys0
  python:
    python_setup:
      version: 3
