---
# vi: ts=2 sw=2 et:

extraction:
  cpp:
    prepare:
      packages:
        - libpwquality-dev
        - libfdisk-dev
        - libp11-kit-dev
        - libssl-dev
        - python3-jinja2
    after_prepare:
      - pip3 install meson==0.53.2
  python:
    python_setup:
      version: 3
