extraction:
  cpp:
    prepare:
      packages:
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - libpwquality-dev
        - libfdisk-dev
        - libp11-kit-dev
        - libssl-dev
    after_prepare:
      - pip3 install meson
      - export PATH="$HOME/.local/bin/:$PATH"
    before_index:
      - export TMPDIR=/var/tmp
    index:
      build_command:
        - meson setup --errorlogs build
        - cat build/meson-logs/meson-log.txt
        - false
  python:
    python_setup:
      version: 3
