---
# vi: ts=2 sw=2 et:

# Explicitly enable certain checks which are hidden by default
queries:
  - include: cpp/declaration-hides-variable
  - include: cpp/inconsistent-null-check
  - include: cpp/mistyped-function-arguments
  - include: cpp/sizeof-side-effect
  - include: cpp/unused-local-variable
  - include:
      tags:
        - "security"
        - "correctness"
      severity: "error"

extraction:
  cpp:
    prepare:
      packages:
        - libpwquality-dev
        - libfdisk-dev
        - libp11-kit-dev
        - libssl-dev
        - python3-jinja2
    after_prepare:
      - pip3 install meson==0.53.2
      - export PATH="/opt/work/.local/bin:$PATH"
  python:
    python_setup:
      version: 3
