---
# SPDX-License-Identifier: LGPL-2.1-or-later
# Docs: https://packit.dev/docs/

# `git describe` returns in systemd's case 'v245-xxx' which breaks RPM version
# detection (that expects 245-xxxx'). Let's tweak the version string accordingly
specfile_path: systemd.spec
files_to_sync:
  - .packit.yml
  - systemd.spec
upstream_tag_template: "v{version}"

actions:
  get-current-version:
    - "cat meson.version"

  post-upstream-clone:
    # Use the Fedora Rawhide specfile.
    - curl -L https://src.fedoraproject.org/rpms/systemd/raw/rawhide/f/systemd.spec --output systemd.template
    - echo "%bcond upstream 1" >>systemd.macros
    - echo "%define meson_extra_configure_options --werror" >>systemd.macros
    - cat systemd.macros systemd.template >systemd.spec

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-aarch64
  - fedora-rawhide-i386
  - fedora-rawhide-ppc64le
  - fedora-rawhide-s390x
  - fedora-rawhide-x86_64

- job: tests
  trigger: pull_request
  fmf_path: test/fmf
  tmt_plan: ci
  targets:
  - fedora-rawhide-x86_64
