---
# vi: ts=2 sw=2 et:
#
name: Build test
on:
  pull_request:
    paths:
      - '**/meson.build'
      - '.github/workflows/**'
      - 'meson_options.txt'
      - 'src/**'
      - 'test/fuzz/**'
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - { COMPILER: "gcc",   COMPILER_VERSION: "10" }
          - { COMPILER: "clang", COMPILER_VERSION: "10" }
          - { COMPILER: "clang", COMPILER_VERSION: "11" }
    env: ${{ matrix.env }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp, python
          queries: ./.lgtm/cpp-queries

      - name: Build check (${{ env.COMPILER }}-${{ env.COMPILER_VERSION }})
        run: sudo -E .github/workflows/ubuntu-build-check.sh

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
